FROM python:3.13-slim

WORKDIR /app

# Install system packages (e.g., git)
RUN apt-get update && apt-get install -y git && apt-get upgrade -y

# Install Python libraries directly
RUN pip install --no-cache-dir requests pyfiglet
RUN pip install --no-cache-dir requests pandas
RUN pip install --no-cache-dir requests matplotlib

# Clone the Git repository
RUN git clone https://github.com/vetronics/shopping_manager.git \
    && mv shopping_manager/* . \
    && rm -rf shopping_manager

# Run the app
CMD ["python", "shopping_manager.py"]
